# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminestimate',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
