# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameters', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False, help_text='Отметьте галочкой, если необходимо обязательно добавить изделие', verbose_name='Обязательное устройство')),
                ('nmb', models.IntegerField(default=1, help_text='Укажите колличество выбранных дополнительных изделий которые должны автоматически добавляться', verbose_name='Колличество')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновленно')),
            ],
            options={
                'verbose_name': 'Дополнительное изделие',
                'verbose_name_plural': 'Дополнительные изделия',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Серия')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Название')),
                ('vendor_code', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Артикул')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Описание')),
                ('voltage', models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='Напряжение [В]')),
                ('current', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Ток [А]')),
                ('type_current', models.CharField(blank=True, default=None, max_length=3, null=True, verbose_name='Вид тока')),
                ('power', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Мощность [кВт]')),
                ('force_input', models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='Силовые входы [шт]')),
                ('discret_input', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Дискретные входы [шт]')),
                ('discret_output', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Дискретные выходы [шт]')),
                ('analog_input', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Аналоговые входы [шт]')),
                ('analog_output', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Аналоговые выходы [шт]')),
                ('temperature_input', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Температурные входы [шт]')),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Высота')),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ширина')),
                ('depth', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Глубина')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('currency', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Валюта')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновленно')),
                ('atributes', models.ManyToManyField(blank=True, default=None, to='parameters.Atribute', verbose_name='Атрибуты изделия')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
            ],
            options={
                'verbose_name': 'Категория изделия',
                'verbose_name_plural': 'Категории изделий',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items_images/', verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновленно')),
                ('item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='items.Item', verbose_name='Изделие')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='ItemManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, default=None, max_length=5, null=True, verbose_name='Сокращение')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
            ],
            options={
                'verbose_name': 'Производитель изделия',
                'verbose_name_plural': 'Производители изделий',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='items.ItemCategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='items.ItemManufacturer', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='additem',
            name='adding_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adding_item', to='items.Item', verbose_name='Дополнительное изделие'),
        ),
        migrations.AddField(
            model_name='additem',
            name='main_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_item', to='items.Item', verbose_name='Основное изделие'),
        ),
        migrations.AlterUniqueTogether(
            name='additem',
            unique_together=set([('main_item', 'adding_item')]),
        ),
    ]
