# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='power_input',
        ),
    ]
