# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='atributes',
            field=models.ManyToManyField(blank=True, default=None, to='parameters.Atribute', verbose_name='Атрибуты изделия'),
        ),
    ]
