# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='type_current',
        ),
    ]
