# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0004_auto_20171216_1859'),
        ('items', '0002_item_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='parameters',
        ),
        migrations.AddField(
            model_name='item',
            name='atributes',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='parameters.Atribute', verbose_name='Атрибуты изделия'),
        ),
    ]
