# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_type_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='current',
        ),
    ]
