# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_power_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='power_input',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='Силовые входы [шт]'),
        ),
    ]
