# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20171216_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ethernet',
        ),
        migrations.RemoveField(
            model_name='item',
            name='profibus',
        ),
        migrations.RemoveField(
            model_name='item',
            name='profinet',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rs484',
        ),
    ]
