# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20171227_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='main_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_item', to='items.Item', verbose_name='Основное изделие'),
        ),
    ]
