# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_item_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Ток [А]'),
        ),
    ]
