# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20171207_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно?'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='itemmanufacturer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно?'),
        ),
        migrations.AlterField(
            model_name='itemmanufacturer',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='itemmanufacturer',
            name='short_name',
            field=models.CharField(blank=True, default=None, max_length=5, null=True, verbose_name='Сокращение'),
        ),
    ]
