# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20171207_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vendor_code',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Артикул'),
        ),
    ]
