# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20171219_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additem',
            options={'verbose_name': 'Дополнительное изделие', 'verbose_name_plural': 'Дополнительные изделия'},
        ),
        migrations.AddField(
            model_name='additem',
            name='nmb',
            field=models.IntegerField(default=1, help_text='Укажите колличество выбранных дополнительных изделий которые должны автоматически добавляться', verbose_name='Колличество'),
        ),
        migrations.AlterField(
            model_name='additem',
            name='adding_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='add_item', to='items.Item', verbose_name='Дополнительное изделие'),
        ),
        migrations.AlterField(
            model_name='additem',
            name='main_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_item', to='items.Item', verbose_name='Основное изделие'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='items.ItemCategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacturer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='items.ItemManufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='items.Item', verbose_name='Изделие'),
        ),
    ]
