# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_power_input'),
        ('items', '0005_item_vendor_code'),
    ]

    operations = [
    ]
