# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20171220_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additem',
            name='is_active',
        ),
    ]
