# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20180110_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='protect_class',
            field=models.CharField(blank=True, choices=[('10', '10'), ('20', '20'), ('30', '30'), ('40', '40')], default='10', max_length=3, null=True, verbose_name='Класс тепловой защиты'),
        ),
    ]
