# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcategoryparameter',
            old_name='item_paramater_bypass',
            new_name='bypass',
        ),
        migrations.RenameField(
            model_name='itemcategoryparameter',
            old_name='item_paramater_revers',
            new_name='revers',
        ),
    ]
