# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategoryParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновленно')),
                ('item_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.ItemCategory', verbose_name='Категория изделия')),
                ('parameter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameters.Parameter', verbose_name='Изделие')),
            ],
            options={
                'verbose_name': 'Категория изделия в параметре',
                'verbose_name_plural': 'Категории изделий в параметрах',
            },
        ),
        migrations.RenameModel(
            old_name='ParameterCategory',
            new_name='CategoryParameter',
        ),
    ]
