# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_auto_20171215_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategoryparameter',
            name='nmb',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itemcategoryparameter',
            name='parameter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameters.Parameter', verbose_name='Тип пуска'),
        ),
    ]
