# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_auto_20171226_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcategoryparameter',
            old_name='item_paramater_do_more',
            new_name='do_more',
        ),
    ]
