# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0003_auto_20171216_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Название')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Величина')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновленно')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
            },
        ),
        migrations.CreateModel(
            name='CategoryAtribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
            ],
            options={
                'verbose_name': 'Категория атрибута',
                'verbose_name_plural': 'Категории атрибутов',
            },
        ),
        migrations.AddField(
            model_name='atribute',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameters.CategoryAtribute', verbose_name='Категория'),
        ),
    ]
